version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    container_name: mvc-backend

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    container_name: mvc-frontend
